# Generated by Django 3.0.6 on 2020-05-15 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_user_relation',
            name='did_try',
        ),
    ]
